#used only when the starts with subversion profile
spring.cloud.config.server.svn:
  uri: ${AIT_REPO_URI:}
  username: ${AIT_REPO_USERNAME:}
  password: ${AIT_REPO_PASSWORD:}
  default-label: ${AIT_REPO_DEFAULT_LABEL:}
  searchPaths: '{profile}'